from causal_engine.models import (
    EdgePolarity,
    FcmEdge,
    FcmGraph,
    FcmNode,
    FcmSnapshot,
    NodeType,
)


def build_reference_port_graph() -> FcmGraph:
    """Build the shared reference graph used by the prototype."""
    return FcmGraph(
        id="graph_terminal_alpha_reference",
        terminal_id="terminal_alpha",
        nodes=[
            FcmNode(
                id="import_volume_pressure",
                label="Import Volume Pressure",
                node_type=NodeType.EXTERNAL_CONTEXT,
                subsystem="external_context",
            ),
            FcmNode(
                id="vessel_bunching",
                label="Vessel Bunching",
                node_type=NodeType.EXTERNAL_CONTEXT,
                subsystem="external_context",
            ),
            FcmNode(
                id="weather_severity",
                label="Weather Severity",
                node_type=NodeType.EXTERNAL_CONTEXT,
                subsystem="external_context",
            ),
            FcmNode(
                id="vessel_arrival_delay",
                label="Vessel Arrival Delay",
                node_type=NodeType.EXTERNAL_CONTEXT,
                subsystem="vessel_operations",
            ),
            FcmNode(
                id="gate_throughput",
                label="Gate Throughput",
                node_type=NodeType.PERFORMANCE_KPI,
                subsystem="gate",
            ),
            FcmNode(
                id="gate_queue_length",
                label="Gate Queue Length",
                node_type=NodeType.DELAY_FACTOR,
                subsystem="gate",
            ),
            FcmNode(
                id="truck_arrival_peaking",
                label="Truck Arrival Peaking",
                node_type=NodeType.EXTERNAL_CONTEXT,
                subsystem="gate",
            ),
            FcmNode(
                id="truck_appointment_compliance",
                label="Truck Appointment Compliance",
                node_type=NodeType.INTERVENTION_VARIABLE,
                subsystem="gate",
            ),
            FcmNode(
                id="document_error_rate",
                label="Document Error Rate",
                node_type=NodeType.DELAY_FACTOR,
                subsystem="gate",
            ),
            FcmNode(
                id="gate_exception_rate",
                label="Gate Exception Rate",
                node_type=NodeType.DELAY_FACTOR,
                subsystem="gate",
            ),
            FcmNode(
                id="chassis_availability",
                label="Chassis Availability",
                node_type=NodeType.RESOURCE_AVAILABILITY,
                subsystem="landside",
            ),
            FcmNode(
                id="warehouse_capacity_pressure",
                label="Warehouse Capacity Pressure",
                node_type=NodeType.EXTERNAL_CONTEXT,
                subsystem="landside",
            ),
            FcmNode(
                id="import_dwell_time",
                label="Import Dwell Time",
                node_type=NodeType.STATE_KPI,
                subsystem="yard",
            ),
            FcmNode(
                id="berth_occupancy",
                label="Berth Occupancy",
                node_type=NodeType.STATE_KPI,
                subsystem="berth",
            ),
            FcmNode(
                id="yard_density",
                label="Yard Density",
                node_type=NodeType.STATE_KPI,
                subsystem="yard",
            ),
            FcmNode(
                id="yard_rehandle_rate",
                label="Yard Rehandle Rate",
                node_type=NodeType.DELAY_FACTOR,
                subsystem="yard",
            ),
            FcmNode(
                id="yard_crane_availability",
                label="Yard Crane Availability",
                node_type=NodeType.RESOURCE_AVAILABILITY,
                subsystem="yard",
            ),
            FcmNode(
                id="empty_container_imbalance",
                label="Empty Container Imbalance",
                node_type=NodeType.STATE_KPI,
                subsystem="yard",
            ),
            FcmNode(
                id="truck_travel_time",
                label="Internal Truck Travel Time",
                node_type=NodeType.DELAY_FACTOR,
                subsystem="internal_transport",
            ),
            FcmNode(
                id="truck_turn_time",
                label="Truck Turn Time",
                node_type=NodeType.PERFORMANCE_KPI,
                subsystem="gate",
            ),
            FcmNode(
                id="qc_waiting",
                label="QC Waiting",
                node_type=NodeType.DELAY_FACTOR,
                subsystem="quay",
            ),
            FcmNode(
                id="qc_productivity",
                label="QC Productivity",
                node_type=NodeType.PERFORMANCE_KPI,
                subsystem="quay",
            ),
            FcmNode(
                id="crane_equipment_availability",
                label="Crane Equipment Availability",
                node_type=NodeType.RESOURCE_AVAILABILITY,
                subsystem="quay",
            ),
            FcmNode(
                id="labor_availability",
                label="Labor Availability",
                node_type=NodeType.RESOURCE_AVAILABILITY,
                subsystem="quay",
            ),
            FcmNode(
                id="berth_productivity",
                label="Berth Productivity",
                node_type=NodeType.PERFORMANCE_KPI,
                subsystem="berth",
            ),
            FcmNode(
                id="vessel_turnaround_time",
                label="Vessel Turnaround Time",
                node_type=NodeType.PERFORMANCE_KPI,
                subsystem="vessel_operations",
            ),
        ],
        edges=[
            FcmEdge(
                id="edge_weather_to_truck_travel_time",
                source_node_id="weather_severity",
                target_node_id="truck_travel_time",
                base_weight=0.24,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.72,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_transport",
            ),
            FcmEdge(
                id="edge_weather_to_qc_productivity",
                source_node_id="weather_severity",
                target_node_id="qc_productivity",
                base_weight=-0.18,
                polarity=EdgePolarity.NEGATIVE,
                confidence=0.70,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_quay",
            ),
            FcmEdge(
                id="edge_weather_to_vessel_turnaround_time",
                source_node_id="weather_severity",
                target_node_id="vessel_turnaround_time",
                base_weight=0.22,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.68,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_vessel",
            ),
            FcmEdge(
                id="edge_weather_to_yard_density",
                source_node_id="weather_severity",
                target_node_id="yard_density",
                base_weight=0.18,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.64,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_yard",
            ),
            FcmEdge(
                id="edge_arrival_delay_to_qc_waiting",
                source_node_id="vessel_arrival_delay",
                target_node_id="qc_waiting",
                base_weight=0.30,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.66,
                evidence_level="synthetic_ground_truth",
                subsystem="vessel_to_quay",
            ),
            FcmEdge(
                id="edge_chassis_availability_to_gate_throughput",
                source_node_id="chassis_availability",
                target_node_id="gate_throughput",
                base_weight=0.46,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.78,
                evidence_level="synthetic_ground_truth",
                subsystem="landside_to_gate",
            ),
            FcmEdge(
                id="edge_gate_throughput_to_import_dwell_time",
                source_node_id="gate_throughput",
                target_node_id="import_dwell_time",
                base_weight=-0.50,
                polarity=EdgePolarity.NEGATIVE,
                lag_minutes=30,
                confidence=0.80,
                evidence_level="synthetic_ground_truth",
                subsystem="gate_to_yard",
            ),
            FcmEdge(
                id="edge_warehouse_capacity_pressure_to_import_dwell_time",
                source_node_id="warehouse_capacity_pressure",
                target_node_id="import_dwell_time",
                base_weight=0.45,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=60,
                confidence=0.76,
                evidence_level="synthetic_ground_truth",
                subsystem="landside_to_yard",
            ),
            FcmEdge(
                id="edge_import_dwell_time_to_yard_density",
                source_node_id="import_dwell_time",
                target_node_id="yard_density",
                base_weight=0.56,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.84,
                evidence_level="synthetic_ground_truth",
                subsystem="yard",
            ),
            FcmEdge(
                id="edge_import_volume_pressure_to_yard_density",
                source_node_id="import_volume_pressure",
                target_node_id="yard_density",
                base_weight=0.44,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.78,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_yard",
            ),
            FcmEdge(
                id="edge_vessel_bunching_to_berth_occupancy",
                source_node_id="vessel_bunching",
                target_node_id="berth_occupancy",
                base_weight=0.50,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.78,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_berth",
            ),
            FcmEdge(
                id="edge_berth_occupancy_to_yard_density",
                source_node_id="berth_occupancy",
                target_node_id="yard_density",
                base_weight=0.42,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.76,
                evidence_level="synthetic_ground_truth",
                subsystem="berth_to_yard",
            ),
            FcmEdge(
                id="edge_berth_occupancy_to_vessel_turnaround_time",
                source_node_id="berth_occupancy",
                target_node_id="vessel_turnaround_time",
                base_weight=0.34,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.74,
                evidence_level="synthetic_ground_truth",
                subsystem="berth_to_vessel",
            ),
            FcmEdge(
                id="edge_yard_density_to_yard_rehandle_rate",
                source_node_id="yard_density",
                target_node_id="yard_rehandle_rate",
                base_weight=0.52,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.80,
                evidence_level="synthetic_ground_truth",
                subsystem="yard",
            ),
            FcmEdge(
                id="edge_yard_density_to_truck_travel_time",
                source_node_id="yard_density",
                target_node_id="truck_travel_time",
                base_weight=0.58,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.82,
                evidence_level="synthetic_ground_truth",
                subsystem="yard_to_transport",
            ),
            FcmEdge(
                id="edge_yard_rehandle_rate_to_truck_travel_time",
                source_node_id="yard_rehandle_rate",
                target_node_id="truck_travel_time",
                base_weight=0.36,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.76,
                evidence_level="synthetic_ground_truth",
                subsystem="yard_to_transport",
            ),
            FcmEdge(
                id="edge_yard_crane_availability_to_truck_travel_time",
                source_node_id="yard_crane_availability",
                target_node_id="truck_travel_time",
                base_weight=-0.40,
                polarity=EdgePolarity.NEGATIVE,
                lag_minutes=15,
                confidence=0.78,
                evidence_level="synthetic_ground_truth",
                subsystem="yard_to_transport",
            ),
            FcmEdge(
                id="edge_truck_travel_time_to_qc_waiting",
                source_node_id="truck_travel_time",
                target_node_id="qc_waiting",
                base_weight=0.55,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.79,
                evidence_level="synthetic_ground_truth",
                subsystem="transport_to_quay",
            ),
            FcmEdge(
                id="edge_crane_equipment_availability_to_qc_productivity",
                source_node_id="crane_equipment_availability",
                target_node_id="qc_productivity",
                base_weight=0.48,
                polarity=EdgePolarity.POSITIVE,
                confidence=0.80,
                evidence_level="synthetic_ground_truth",
                subsystem="quay",
            ),
            FcmEdge(
                id="edge_labor_availability_to_qc_productivity",
                source_node_id="labor_availability",
                target_node_id="qc_productivity",
                base_weight=0.36,
                polarity=EdgePolarity.POSITIVE,
                confidence=0.74,
                evidence_level="synthetic_ground_truth",
                subsystem="quay",
            ),
            FcmEdge(
                id="edge_qc_waiting_to_qc_productivity",
                source_node_id="qc_waiting",
                target_node_id="qc_productivity",
                base_weight=-0.62,
                polarity=EdgePolarity.NEGATIVE,
                confidence=0.84,
                evidence_level="synthetic_ground_truth",
                subsystem="quay",
            ),
            FcmEdge(
                id="edge_qc_waiting_to_berth_occupancy",
                source_node_id="qc_waiting",
                target_node_id="berth_occupancy",
                base_weight=0.28,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.69,
                evidence_level="synthetic_ground_truth",
                subsystem="quay_to_berth",
            ),
            FcmEdge(
                id="edge_qc_waiting_to_vessel_turnaround_time",
                source_node_id="qc_waiting",
                target_node_id="vessel_turnaround_time",
                base_weight=0.36,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.80,
                evidence_level="synthetic_ground_truth",
                subsystem="quay_to_vessel",
            ),
            FcmEdge(
                id="edge_qc_productivity_to_berth_productivity",
                source_node_id="qc_productivity",
                target_node_id="berth_productivity",
                base_weight=0.58,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.82,
                evidence_level="synthetic_ground_truth",
                subsystem="quay_to_berth",
            ),
            FcmEdge(
                id="edge_qc_productivity_to_vessel_turnaround_time",
                source_node_id="qc_productivity",
                target_node_id="vessel_turnaround_time",
                base_weight=-0.52,
                polarity=EdgePolarity.NEGATIVE,
                lag_minutes=30,
                confidence=0.83,
                evidence_level="synthetic_ground_truth",
                subsystem="quay_to_vessel",
            ),
            FcmEdge(
                id="edge_truck_arrival_peaking_to_gate_queue_length",
                source_node_id="truck_arrival_peaking",
                target_node_id="gate_queue_length",
                base_weight=0.50,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.78,
                evidence_level="synthetic_ground_truth",
                subsystem="gate",
            ),
            FcmEdge(
                id="edge_truck_appointment_compliance_to_gate_queue_length",
                source_node_id="truck_appointment_compliance",
                target_node_id="gate_queue_length",
                base_weight=-0.42,
                polarity=EdgePolarity.NEGATIVE,
                lag_minutes=15,
                confidence=0.76,
                evidence_level="synthetic_ground_truth",
                subsystem="gate",
            ),
            FcmEdge(
                id="edge_document_error_rate_to_gate_exception_rate",
                source_node_id="document_error_rate",
                target_node_id="gate_exception_rate",
                base_weight=0.55,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.82,
                evidence_level="synthetic_ground_truth",
                subsystem="gate",
            ),
            FcmEdge(
                id="edge_gate_exception_rate_to_gate_throughput",
                source_node_id="gate_exception_rate",
                target_node_id="gate_throughput",
                base_weight=-0.48,
                polarity=EdgePolarity.NEGATIVE,
                lag_minutes=15,
                confidence=0.80,
                evidence_level="synthetic_ground_truth",
                subsystem="gate",
            ),
            FcmEdge(
                id="edge_gate_queue_length_to_truck_turn_time",
                source_node_id="gate_queue_length",
                target_node_id="truck_turn_time",
                base_weight=0.45,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.80,
                evidence_level="synthetic_ground_truth",
                subsystem="gate",
            ),
            FcmEdge(
                id="edge_yard_density_to_truck_turn_time",
                source_node_id="yard_density",
                target_node_id="truck_turn_time",
                base_weight=0.34,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.78,
                evidence_level="synthetic_ground_truth",
                subsystem="yard_to_gate",
            ),
            FcmEdge(
                id="edge_truck_travel_time_to_truck_turn_time",
                source_node_id="truck_travel_time",
                target_node_id="truck_turn_time",
                base_weight=0.42,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.80,
                evidence_level="synthetic_ground_truth",
                subsystem="transport_to_gate",
            ),
            FcmEdge(
                id="edge_truck_turn_time_to_gate_throughput",
                source_node_id="truck_turn_time",
                target_node_id="gate_throughput",
                base_weight=-0.36,
                polarity=EdgePolarity.NEGATIVE,
                lag_minutes=15,
                confidence=0.74,
                evidence_level="synthetic_ground_truth",
                subsystem="gate",
            ),
        ],
    )


def build_reference_port_snapshot() -> FcmSnapshot:
    return FcmSnapshot(
        snapshot_id="snap_current_shift_reference",
        terminal_id="terminal_alpha",
        node_values={
            "import_volume_pressure": 0.20,
            "vessel_bunching": 0.20,
            "weather_severity": 0.20,
            "vessel_arrival_delay": 0.15,
            "gate_throughput": -0.15,
            "gate_queue_length": 0.25,
            "truck_arrival_peaking": 0.25,
            "truck_appointment_compliance": -0.05,
            "document_error_rate": 0.10,
            "gate_exception_rate": 0.12,
            "chassis_availability": -0.10,
            "warehouse_capacity_pressure": 0.20,
            "import_dwell_time": 0.45,
            "berth_occupancy": 0.65,
            "yard_density": 0.55,
            "yard_rehandle_rate": 0.40,
            "yard_crane_availability": -0.05,
            "empty_container_imbalance": 0.15,
            "truck_travel_time": 0.40,
            "truck_turn_time": 0.45,
            "qc_waiting": 0.35,
            "qc_productivity": -0.10,
            "crane_equipment_availability": 0.05,
            "labor_availability": 0.05,
            "berth_productivity": -0.10,
            "vessel_turnaround_time": 0.30,
        },
    )
