from causal_engine.models import (
    EdgePolarity,
    FcmEdge,
    FcmGraph,
    FcmNode,
    FcmSnapshot,
    NodeType,
)


def build_reference_port_graph() -> FcmGraph:
    """Build the shared eight-node reference graph used by the prototype."""
    return FcmGraph(
        id="graph_terminal_alpha_reference",
        terminal_id="terminal_alpha",
        nodes=[
            FcmNode(
                id="weather_severity",
                label="Weather Severity",
                node_type=NodeType.EXTERNAL_CONTEXT,
                subsystem="external_context",
            ),
            FcmNode(
                id="vessel_arrival_delay",
                label="Vessel Arrival Delay",
                node_type=NodeType.EXTERNAL_CONTEXT,
                subsystem="vessel_operations",
            ),
            FcmNode(
                id="berth_occupancy",
                label="Berth Occupancy",
                node_type=NodeType.STATE_KPI,
                subsystem="berth",
            ),
            FcmNode(
                id="yard_density",
                label="Yard Density",
                node_type=NodeType.STATE_KPI,
                subsystem="yard",
            ),
            FcmNode(
                id="truck_travel_time",
                label="Internal Truck Travel Time",
                node_type=NodeType.DELAY_FACTOR,
                subsystem="internal_transport",
            ),
            FcmNode(
                id="qc_waiting",
                label="QC Waiting",
                node_type=NodeType.DELAY_FACTOR,
                subsystem="quay",
            ),
            FcmNode(
                id="qc_productivity",
                label="QC Productivity",
                node_type=NodeType.PERFORMANCE_KPI,
                subsystem="quay",
            ),
            FcmNode(
                id="vessel_turnaround_time",
                label="Vessel Turnaround Time",
                node_type=NodeType.PERFORMANCE_KPI,
                subsystem="vessel_operations",
            ),
        ],
        edges=[
            FcmEdge(
                id="edge_weather_to_truck_travel_time",
                source_node_id="weather_severity",
                target_node_id="truck_travel_time",
                base_weight=0.24,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.72,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_transport",
            ),
            FcmEdge(
                id="edge_weather_to_qc_productivity",
                source_node_id="weather_severity",
                target_node_id="qc_productivity",
                base_weight=-0.18,
                polarity=EdgePolarity.NEGATIVE,
                confidence=0.70,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_quay",
            ),
            FcmEdge(
                id="edge_weather_to_vessel_turnaround_time",
                source_node_id="weather_severity",
                target_node_id="vessel_turnaround_time",
                base_weight=0.22,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.68,
                evidence_level="synthetic_ground_truth",
                subsystem="external_to_vessel",
            ),
            FcmEdge(
                id="edge_arrival_delay_to_qc_waiting",
                source_node_id="vessel_arrival_delay",
                target_node_id="qc_waiting",
                base_weight=0.30,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.66,
                evidence_level="synthetic_ground_truth",
                subsystem="vessel_to_quay",
            ),
            FcmEdge(
                id="edge_berth_occupancy_to_yard_density",
                source_node_id="berth_occupancy",
                target_node_id="yard_density",
                base_weight=0.42,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.76,
                evidence_level="synthetic_ground_truth",
                subsystem="berth_to_yard",
            ),
            FcmEdge(
                id="edge_berth_occupancy_to_vessel_turnaround_time",
                source_node_id="berth_occupancy",
                target_node_id="vessel_turnaround_time",
                base_weight=0.34,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.74,
                evidence_level="synthetic_ground_truth",
                subsystem="berth_to_vessel",
            ),
            FcmEdge(
                id="edge_yard_density_to_truck_travel_time",
                source_node_id="yard_density",
                target_node_id="truck_travel_time",
                base_weight=0.58,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.82,
                evidence_level="synthetic_ground_truth",
                subsystem="yard_to_transport",
            ),
            FcmEdge(
                id="edge_truck_travel_time_to_qc_waiting",
                source_node_id="truck_travel_time",
                target_node_id="qc_waiting",
                base_weight=0.55,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.79,
                evidence_level="synthetic_ground_truth",
                subsystem="transport_to_quay",
            ),
            FcmEdge(
                id="edge_qc_waiting_to_qc_productivity",
                source_node_id="qc_waiting",
                target_node_id="qc_productivity",
                base_weight=-0.62,
                polarity=EdgePolarity.NEGATIVE,
                confidence=0.84,
                evidence_level="synthetic_ground_truth",
                subsystem="quay",
            ),
            FcmEdge(
                id="edge_qc_waiting_to_berth_occupancy",
                source_node_id="qc_waiting",
                target_node_id="berth_occupancy",
                base_weight=0.28,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=30,
                confidence=0.69,
                evidence_level="synthetic_ground_truth",
                subsystem="quay_to_berth",
            ),
            FcmEdge(
                id="edge_qc_waiting_to_vessel_turnaround_time",
                source_node_id="qc_waiting",
                target_node_id="vessel_turnaround_time",
                base_weight=0.36,
                polarity=EdgePolarity.POSITIVE,
                lag_minutes=15,
                confidence=0.80,
                evidence_level="synthetic_ground_truth",
                subsystem="quay_to_vessel",
            ),
            FcmEdge(
                id="edge_qc_productivity_to_vessel_turnaround_time",
                source_node_id="qc_productivity",
                target_node_id="vessel_turnaround_time",
                base_weight=-0.52,
                polarity=EdgePolarity.NEGATIVE,
                lag_minutes=30,
                confidence=0.83,
                evidence_level="synthetic_ground_truth",
                subsystem="quay_to_vessel",
            ),
        ],
    )


def build_reference_port_snapshot() -> FcmSnapshot:
    return FcmSnapshot(
        snapshot_id="snap_current_shift_reference",
        terminal_id="terminal_alpha",
        node_values={
            "weather_severity": 0.20,
            "vessel_arrival_delay": 0.15,
            "berth_occupancy": 0.65,
            "yard_density": 0.55,
            "truck_travel_time": 0.40,
            "qc_waiting": 0.35,
            "qc_productivity": -0.10,
            "vessel_turnaround_time": 0.30,
        },
    )
